const testData = {
  leagues: [
    {
      leagueName: 'League Name 1',
      teamName: ' Team Name 1',
      draftDate: '2024-06-11',
      platform: 'espn',
      teamCount: '16',
      pickPosition: '6',
      buyIn: '21',
      initialRank: '10',
      currentRank: '10',
      playoffTeams: '6',
      payout1: '126',
      payout2: '40',
      payout3: '10',
    },
    {
      leagueName: 'League Name 2',
      teamName: ' Team Name 2',
      draftDate: '2024-06-11',
      platform: 'espn',
      teamCount: '16',
      pickPosition: '6',
      buyIn: '21',
      initialRank: '10',
      currentRank: '10',
      playoffTeams: '6',
      payout1: '126',
      payout2: '40',
      payout3: '10',
    },
    {
      leagueName: 'League Name 3',
      teamName: ' Team Name 3',
      draftDate: '2024-06-11',
      platform: 'espn',
      teamCount: '16',
      pickPosition: '6',
      buyIn: '21',
      initialRank: '10',
      currentRank: '10',
      playoffTeams: '6',
      payout1: '126',
      payout2: '40',
      payout3: '10',
    },
    {
      leagueName: 'League Name 4',
      teamName: ' Team Name 4',
      draftDate: '2024-06-11',
      platform: 'espn',
      teamCount: '16',
      pickPosition: '6',
      buyIn: '21',
      initialRank: '10',
      currentRank: '10',
      playoffTeams: '6',
      payout1: '126',
      payout2: '40',
      payout3: '10',
    },
    {
      leagueName: 'League Name 5',
      teamName: ' Team Name 5',
      draftDate: '2024-06-11',
      platform: 'espn',
      teamCount: '16',
      pickPosition: '6',
      buyIn: '21',
      initialRank: '10',
      currentRank: '10',
      playoffTeams: '6',
      payout1: '126',
      payout2: '40',
      payout3: '10',
    },
  ],
}

export default testData
